### PR TITLE
For pr

### PR DESCRIPTION
**Pull request by lupa18**
This is an easy way to execute the 3 badger-scripts
It only one file and can be run from root ivl folder
I hope be useful

### CODE REVIEW

**Comment by vecna** [comment]
I'll document it on the README and do the test soon. thanks

**Comment by vecna** [comment]
@lupa18 in which distribution has been tested?

**Comment by lupa18** [comment]
```
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**Comment by vecna** [comment]
Sorry! I was forgetting to merge this

**Pull request merged**
